### ISSUE TITLE
SOM_Variable_Tableの修正

### ISSUE THREAD

**Issue by ae14watanabe** [furukawa-laboratory/som_family_workout#1]
**対象となるファイル**
https://github.com/furukawa-laboratory/som_family_workout/blob/master/SOM/SOM_Variable_Table.pdf

添削してみたので修正お願いします
[Corrected_by_W_SOM_Variable_Table.pdf](https://github.com/furukawa-laboratory/som_family_workout/files/3470727/Corrected_by_W_SOM_Variable_Table.pdf)

**Comment by ae14watanabe** [comment]
添削していること以外にも、Dropbox paperの内容など、スライドとこのpdfを見れば実装できる、っていうレベルに持って行くのが理想かな。
資料が散らばっているのはあまり良い状態じゃないと思うので…

**Comment by ae14watanabe** [comment]
プルリク出してくれればreviewします！

**Comment by kpasso1015** [comment]
@ae14watanabe 
> 添削していること以外にも、Dropbox paperの内容など、スライドとこのpdfを見れば実装できる、っていうレベルに持って行くのが理想かな。
資料が散らばっているのはあまり良い状態じゃないと思うので…

ありがとうございます!
できるだけ早急に取り掛かります...!

**Comment by kpasso1015** [comment]
@ae14watanabe 
\zeta の行列化として文字を探しているんですが、この中にありますでしょうか???

![image](https://user-images.githubusercontent.com/12492226/62760233-7621f400-babe-11e9-8b84-ca860d7b05b5.png)
![image](https://user-images.githubusercontent.com/12492226/62760245-7c17d500-babe-11e9-9a2e-3a9eb75bb8bf.png)
![image](https://user-images.githubusercontent.com/12492226/62760253-81751f80-babe-11e9-9e0e-fa1ecd21f024.png)

**Comment by ae14watanabe** [comment]
一番下じゃないですかね、多分

**Comment by ae14watanabe** [comment]
なぜkの添え字が

**Comment by ae14watanabe** [comment]
ゼータの大文字まじ厳ついよねー

**Comment by kpasso1015** [comment]
zeta の大文字が一番上?で
なんか引っ掛けたようで、申し訳ないんです下けど、一番下のXi(グザイ) なんですよね...
離散化した後の潜在変数 を xiってするんだったらきもてぃーなんですよね...

**Comment by ae14watanabe** [comment]
あれそうだったっけ？恥ずかし

**Comment by kpasso1015** [comment]
![image](https://user-images.githubusercontent.com/12492226/62761045-889d2d00-bac0-11e9-95c4-482b84656e98.png)

**Comment by ae14watanabe** [comment]
そうかzetaの大文字はZだからふつーにかぶるんか

**Comment by ae14watanabe** [comment]
\tilde{Z}とかでいいんじゃない？

**Comment by ae14watanabe** [comment]
記号上は

**Comment by ae14watanabe** [comment]
コードはZetaとかでいいでしょ

**Comment by kpasso1015** [comment]
\tilde{Z}　Solution いただきました

**Comment by kpasso1015** [comment]
@ae14watanabe 
![image](https://user-images.githubusercontent.com/12492226/62991211-ac2df200-be89-11e9-95f5-54267215c057.png)

今更なんですが、D次元方向の話の時に縦ベクトルにすると、D x N 行列になっちゃんと思うんですが、それでいいんでかね?

**Comment by ae14watanabe** [comment]
俺ならこうする
![image](https://user-images.githubusercontent.com/19607449/62991452-a389eb80-be8a-11e9-807a-73d1cca2805b.png)

**Comment by ae14watanabe** [comment]
ちなみに文献によってはDxNで定義されてることは珍しくないです、古川研ではNxDが多いけど
